### ISSUE TITLE
[FEATURE] Font size / scale option

### ISSUE THREAD

**Issue by sargant** [TigraTT-Driver/shinretro#29]
This is an extremely beautiful theme, but on a 6" 1080p screen, such as the Odin, a lot of the text is very small. Would it be possible to have the ability to scale the font between a few sizes? Even if it's just a setting I can edit by hand in the code.

**Comment by TigraTT-Driver** [comment]
Hi @sargant 
In general, I think there is nothing against your wish. I just don't have a device with which I could test / recreate this since I don't have a device with a pixel density as high as yours

I think a setting may not be necessary. Theoretically you can query the info of the pixel density of the device, however I am not sure what provides the correct info in your case, i think the second is probably correct:
[devicePixelRatio](https://doc.qt.io/qt-5/qml-qtquick-window-screen.html#devicePixelRatio-attached-prop) or [pixelDensity](https://doc.qt.io/qt-5/qml-qtquick-window-screen.html#pixelDensity-attached-prop)
These information could be used to manipulate the font size dynamically.

If this way is not possible and a setting is necessary:
I reject an implementation to control the behavior via direct intervention in the theme code. In general I think a function of the theme must work without user manipulation of any data in the theme folder. And to control the behavior there is already the settings menu for your case. Therefore I don't know why it should be controlled by the code.

I'll try to get a proof of concept on a testing branch :smile:

**Comment by TigraTT-Driver** [comment]
> Thanks - very happy to be a tester if you need it!

i've published my current testing branch. You can try it if you want.
https://github.com/TigraTT-Driver/shinretro/tree/enh-fontscaling
The scaling of the font can be activated with the new theme setting 'General - Dynamic font scaling'.

If you could give me feedback if the font sizes themselves are suitable would be great :smile: 

Some things still don't look good. E.g. the LB/RB buttons overlap with the menu text if you use XBOX buttons for the display and the font scaling is active.

**Comment by TigraTT-Driver** [comment]
thank you for your feedback i think i got everything now and merge the changes to master :smile:
