### ISSUE TITLE
[BUG] the frame is not the same for all menu

### ISSUE THREAD

**Issue by Sebio1980** [TigraTT-Driver/shinretro#42]
**Describe the bug**
In the settings -> Collections -> Accent colors : 1 or 2
if you choice 1
in the HOME menu you see the frame black
in the COLLECTIONS menu you see the frame Yellow
in the GAMES menu you see the frame Yellow

if you choice 2
in the HOME menu you see the frame blue
in the COLLECTIONS menu you see the frame Black
in the GAMES menu you see the frame Black

**To Reproduce**

**Expected behavior**

**Screenshots**
exp with choice 1
HOME
![image](https://user-images.githubusercontent.com/53249046/182474438-dedb970b-1e48-4d73-a9b7-232aa472737a.png)
COLLECTIONS
![image](https://user-images.githubusercontent.com/53249046/182474551-e790f741-a0b6-42dd-a035-8b732843bed0.png)
GAMES
![image](https://user-images.githubusercontent.com/53249046/182474611-0c6dad7b-1990-4c41-b520-8ab786222b89.png)

**Device (please complete the following information):**
 - OS: [e.g. android] Linux
 - Version [e.g. 10] pixL-b26
 - GPU [nvidia] G-Force 1080

**Additional context**

**Comment by TigraTT-Driver** [comment]
I don't fully get the issue. The selection frame changes color depending on which collection the selected game belongs to.

I handpicked three colors which represent the collection by a distinctive color in its device / game pad / logo or interface:
- primary color of collection. Used for tinted background
- altColor: 10% darker color of primary color. Used for secondary color (selected border) when setting Accent colors is set to 1
- altColor2: Another distinct color of the collection. Ideally, not a similar color as used for primary color. Secondary color (selected border) when setting Accent colors is set to 2

If you select a PS1 game on the home screen like the 'Agent under Fire' which is cut on the screenshot the frame should also get yellow with 'Accent Colors' set to 1. If you select the 'From Russia with Love' the Frame should get purple since it's a gamecube game

**Comment by Sebio1980** [comment]
For the PS1 yes my frame is always yellow. so it's normal. I hadn't noticed the detail that there is a color frame per system.
