### ISSUE TITLE
[FEATURE] add name/logo system in description game in view FAVORITES/LAST PLAYED/All games

### ISSUE THREAD

**Issue by Sebio1980** [TigraTT-Driver/shinretro#64]
**Is your feature request related to a problem? Please describe.**
Hello, it would be nice to have the system name/logo (PlayStation 2/Nintendo GAMECUBE/etc...) for the game highlight in the description part in front of the rating or the name of the company that developed the game.

**Describe the solution you'd like**
because in these views we can have the same game several times on different platforms.
<a href="https://zupimages.net/viewer.php?id=22/42/smhg.jpg"><img src="https://zupimages.net/up/22/42/smhg.jpg" alt="" /></a>

**Additional context**
- in game.qml view FAVORITES/LAST PLAYED/All games

Thank you

**Comment by TigraTT-Driver** [comment]
hmm first solution which comes to my mind is a simple text change in this case:
"Developed by "dev" for "plattform""

**Comment by msheehan79** [comment]
This is actually already implemented in the theme in the same fashion as @TigraTT-Driver mentioned, but it is conditionally shown only when the collectiontype is custom if memory serves. I don't think it would be very difficult to extend this logic to also include the "all games" / "last played" and "favorites" collections too since those do span across systems.

![image](https://user-images.githubusercontent.com/1565622/196850574-1c90d7ed-b19e-4a2f-87d2-df4846da7315.png)
