### ISSUE TITLE
Theme configuration is translated

### ISSUE THREAD

**Issue by j8r** [TigraTT-Driver/shinretro#82]
In `theme_settings/shinretro.json`, for instance when enlgish is set there is `"manuColor":"color"`, but then if I switch to french, it becomes `"manuColor":"Couleur"`. Either way, it still work regardless of the language. However, I think to have a consistent configuration only in english should be preferable.

Note here that "menu" is misspelled to "_manu_". The downside of correcting this word is the existing configurations will break.

**Comment by j8r** [comment]
In addition, I've noticed configurations with `*Index`, like `manuColor` and `manuColorIndex` - what's the purpose?
This will help a lot for those editing the configurations directly on the file to not have this `*Index` fields.

**Comment by j8r** [comment]
In addition, I've noticed configuration fields with `*Index`, like `manuColor` and `manuColorIndex` - what's the purpose?
This will help a lot for those editing the configuration file directly to not have this `*Index` fields.

**Comment by j8r** [comment]
Hopefully, in contrary of other `*Index` fields, the one I want to programmatically edit, `langIndex`, doesn't do anything :slightly_smiling_face: . I only have to edit `lang` to change the language.

**Comment by TigraTT-Driver** [comment]
hi @j8r 
manu is a typo indeed.

The `*index` fields store the selected option regardless of the display value. Without this suffix the display value of the option is always stored. Most options are checked using the index. Some settings where the value is language independent are checked against the display value as is the case with your `lang` example.

The condition comes among other things from when I implemented the language support. I guess this could probably be made better. The entries without index suffix I still let write into the setting file (even if these might not be checked) so that it was better human readable.

**Comment by j8r** [comment]
Thanks for the answer! This behavior is fine for me, since I was mainly interested to edit the language.
