### ISSUE TITLE
[BUG} Scraped videos not working in BoxArt-Grid layout

### ISSUE THREAD

**Issue by bezza191** [TigraTT-Driver/shinretro#89]
**Describe the bug**
Scraped videos work correctly in all areas of the theme, except when the Games Screen is set to the BoxArt-Grid layout.

In BoxArt-Grid mode the video produces audio, but displays only a small grey square where the video should be

**To Reproduce**
1. Toggle Settings > Games > Games layout to [BoxArt-Grid]
2. Go to Games tab

**Expected behavior**
Video should play on the games tab, in the blank space next to the game description

**Screenshots**
![image](https://user-images.githubusercontent.com/37932350/230747675-9f86cdcb-7828-4dc8-b81d-a7928541638a.png)
![image](https://user-images.githubusercontent.com/37932350/230747708-26cc15b8-f82d-4c1c-9289-374e5ccff6a7.png)
![image](https://user-images.githubusercontent.com/37932350/230747770-cb849952-70bb-433d-a99a-c2f42b7aa518.png)

**Device (please complete the following information):**
 - OS: Tried on Linux and in a Windows 10 VM
 - Version: Newest version of Pegasus and theme available

**Additional context**

**Comment by TigraTT-Driver** [comment]
Hi @bezza191 I think the problem is triggered by the absence of screenshot (or titlescreen)  assets for your games. I have not considered this scenario. The size of the preview box is determined by this asset type and the video is adjusted to it if available. Statically setting the box size is not possible because of different possible dimensions. I don't have time to work on the theme at the moment, but I wanted to tell you about a possible workaround.

**Comment by bezza191** [comment]
I appreciate you taking the time to get back to me, will work around it

Thanks
